# -*- coding: utf-8 -*-
"""CHESS_parquet_concat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXj78mp1-Kxd--hTt6ZRaCvpUbt7Z433
"""

import pandas as pd
from os import listdir





df = pd.concat([
    pd.read_parquet(path)
    for path in [
        i for i in listdir()
        if i.endswith("games.parquet")
    ]
])

df.to_parquet("games_25.parquet", index=False)

pd.read_parquet("games_25.parquet")

